#!/usr/bin/env bash
# Local dev install for OpenAgents (macOS/Linux)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

PYTHON="${PYTHON:-python3.11}"
if ! command -v "$PYTHON" >/dev/null 2>&1; then
  PYTHON=python3
fi

LOCAL_BIN="${HOME}/.local/bin"

link_cli_commands() {
  mkdir -p "$LOCAL_BIN"
  local name target
  for name in openagents openagents-run openagents-acp hermes; do
    target="$ROOT/venv/bin/$name"
    if [[ -x "$target" ]]; then
      ln -sf "$target" "$LOCAL_BIN/$name"
      echo "  ✓ $LOCAL_BIN/$name"
    fi
  done
  # Record install location for doctor/update tooling
  mkdir -p "$HOME/.openagents"
  printf '%s\n' "$ROOT" >"$HOME/.openagents/source-install-root"
}

ensure_path_hint() {
  if [[ ":$PATH:" == *":$LOCAL_BIN:"* ]]; then
    return 0
  fi
  echo ""
  echo "⚠  $LOCAL_BIN is not on your PATH yet."
  echo "   Add this line to ~/.zshrc or ~/.bash_profile, then open a new terminal:"
  echo '   export PATH="$HOME/.local/bin:$PATH"'
}

echo "→ Creating venv with $PYTHON..."
if command -v uv >/dev/null 2>&1; then
  uv venv venv --python "$PYTHON"
  # shellcheck disable=SC1091
  source venv/bin/activate
  echo "→ Installing OpenAgents (all extras — may take a few minutes)..."
  uv pip install -e ".[all,dev]"
else
  "$PYTHON" -m venv venv
  # shellcheck disable=SC1091
  source venv/bin/activate
  pip install -U pip wheel
  pip install -e ".[all,dev]"
fi

echo "→ Linking CLI into ~/.local/bin (no 'source venv' needed)..."
link_cli_commands

echo "→ Ensuring ~/.openagents config..."
mkdir -p "$HOME/.openagents"
if [[ ! -f "$HOME/.openagents/config.yaml" ]]; then
  cat >"$HOME/.openagents/config.yaml" <<'EOF'
# OpenAgents — generated by scripts/install-local.sh
display:
  skin: opencode
model:
  provider: auto
EOF
fi

ensure_path_hint

echo ""
echo "✓ Install complete — run from any directory:"
echo ""
echo "  openagents --version"
echo "  openagents doctor"
echo "  openagents model"
echo "  openagents auth add openai-codex"
echo "  openagents"
