#!/usr/bin/env bash
# Local dev install for OpenAgents (macOS/Linux)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

PYTHON="${PYTHON:-python3.11}"
if ! command -v "$PYTHON" >/dev/null 2>&1; then
  PYTHON=python3
fi

echo "→ Creating venv with $PYTHON..."
if command -v uv >/dev/null 2>&1; then
  uv venv venv --python "$PYTHON"
  # shellcheck disable=SC1091
  source venv/bin/activate
  echo "→ Installing OpenAgents (all extras — may take a few minutes)..."
  uv pip install -e ".[all,dev]"
else
  "$PYTHON" -m venv venv
  # shellcheck disable=SC1091
  source venv/bin/activate
  pip install -U pip wheel
  pip install -e ".[all,dev]"
fi

echo "→ Ensuring ~/.openagents config..."
mkdir -p "$HOME/.openagents"
if [[ ! -f "$HOME/.openagents/config.yaml" ]]; then
  cat >"$HOME/.openagents/config.yaml" <<'EOF'
# OpenAgents — generated by scripts/install-local.sh
display:
  skin: opencode
model:
  provider: auto
EOF
fi

echo ""
echo "✓ Install complete."
echo ""
echo "  source $ROOT/venv/bin/activate"
echo "  openagents --version"
echo "  openagents doctor"
echo "  openagents model          # pick provider (OpenAI Codex, OpenRouter, …)"
echo "  openagents auth add openai-codex   # ChatGPT / Codex subscription login"
echo "  openagents                  # interactive chat (OpenCode theme)"
echo "  /skin opencode              # switch theme anytime"
